//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiProject1.DilbertService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gcomputer.net/webservices/", ConfigurationName="DilbertService.DilbertSoap")]
    public interface DilbertSoap {
        
        // CODEGEN: Generating message contract since element name TodaysDilbertResult from namespace http://gcomputer.net/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gcomputer.net/webservices/TodaysDilbert", ReplyAction="*")]
        ApiProject1.DilbertService.TodaysDilbertResponse TodaysDilbert(ApiProject1.DilbertService.TodaysDilbertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gcomputer.net/webservices/TodaysDilbert", ReplyAction="*")]
        System.Threading.Tasks.Task<ApiProject1.DilbertService.TodaysDilbertResponse> TodaysDilbertAsync(ApiProject1.DilbertService.TodaysDilbertRequest request);
        
        // CODEGEN: Generating message contract since element name DailyDilbertResult from namespace http://gcomputer.net/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gcomputer.net/webservices/DailyDilbert", ReplyAction="*")]
        ApiProject1.DilbertService.DailyDilbertResponse DailyDilbert(ApiProject1.DilbertService.DailyDilbertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gcomputer.net/webservices/DailyDilbert", ReplyAction="*")]
        System.Threading.Tasks.Task<ApiProject1.DilbertService.DailyDilbertResponse> DailyDilbertAsync(ApiProject1.DilbertService.DailyDilbertRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TodaysDilbertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TodaysDilbert", Namespace="http://gcomputer.net/webservices/", Order=0)]
        public ApiProject1.DilbertService.TodaysDilbertRequestBody Body;
        
        public TodaysDilbertRequest() {
        }
        
        public TodaysDilbertRequest(ApiProject1.DilbertService.TodaysDilbertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TodaysDilbertRequestBody {
        
        public TodaysDilbertRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TodaysDilbertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TodaysDilbertResponse", Namespace="http://gcomputer.net/webservices/", Order=0)]
        public ApiProject1.DilbertService.TodaysDilbertResponseBody Body;
        
        public TodaysDilbertResponse() {
        }
        
        public TodaysDilbertResponse(ApiProject1.DilbertService.TodaysDilbertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gcomputer.net/webservices/")]
    public partial class TodaysDilbertResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TodaysDilbertResult;
        
        public TodaysDilbertResponseBody() {
        }
        
        public TodaysDilbertResponseBody(string TodaysDilbertResult) {
            this.TodaysDilbertResult = TodaysDilbertResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DailyDilbertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DailyDilbert", Namespace="http://gcomputer.net/webservices/", Order=0)]
        public ApiProject1.DilbertService.DailyDilbertRequestBody Body;
        
        public DailyDilbertRequest() {
        }
        
        public DailyDilbertRequest(ApiProject1.DilbertService.DailyDilbertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gcomputer.net/webservices/")]
    public partial class DailyDilbertRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime ADate;
        
        public DailyDilbertRequestBody() {
        }
        
        public DailyDilbertRequestBody(System.DateTime ADate) {
            this.ADate = ADate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DailyDilbertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DailyDilbertResponse", Namespace="http://gcomputer.net/webservices/", Order=0)]
        public ApiProject1.DilbertService.DailyDilbertResponseBody Body;
        
        public DailyDilbertResponse() {
        }
        
        public DailyDilbertResponse(ApiProject1.DilbertService.DailyDilbertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gcomputer.net/webservices/")]
    public partial class DailyDilbertResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DailyDilbertResult;
        
        public DailyDilbertResponseBody() {
        }
        
        public DailyDilbertResponseBody(string DailyDilbertResult) {
            this.DailyDilbertResult = DailyDilbertResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DilbertSoapChannel : ApiProject1.DilbertService.DilbertSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DilbertSoapClient : System.ServiceModel.ClientBase<ApiProject1.DilbertService.DilbertSoap>, ApiProject1.DilbertService.DilbertSoap {
        
        public DilbertSoapClient() {
        }
        
        public DilbertSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DilbertSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DilbertSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DilbertSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApiProject1.DilbertService.TodaysDilbertResponse ApiProject1.DilbertService.DilbertSoap.TodaysDilbert(ApiProject1.DilbertService.TodaysDilbertRequest request) {
            return base.Channel.TodaysDilbert(request);
        }
        
        public string TodaysDilbert() {
            ApiProject1.DilbertService.TodaysDilbertRequest inValue = new ApiProject1.DilbertService.TodaysDilbertRequest();
            inValue.Body = new ApiProject1.DilbertService.TodaysDilbertRequestBody();
            ApiProject1.DilbertService.TodaysDilbertResponse retVal = ((ApiProject1.DilbertService.DilbertSoap)(this)).TodaysDilbert(inValue);
            return retVal.Body.TodaysDilbertResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApiProject1.DilbertService.TodaysDilbertResponse> ApiProject1.DilbertService.DilbertSoap.TodaysDilbertAsync(ApiProject1.DilbertService.TodaysDilbertRequest request) {
            return base.Channel.TodaysDilbertAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApiProject1.DilbertService.TodaysDilbertResponse> TodaysDilbertAsync() {
            ApiProject1.DilbertService.TodaysDilbertRequest inValue = new ApiProject1.DilbertService.TodaysDilbertRequest();
            inValue.Body = new ApiProject1.DilbertService.TodaysDilbertRequestBody();
            return ((ApiProject1.DilbertService.DilbertSoap)(this)).TodaysDilbertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApiProject1.DilbertService.DailyDilbertResponse ApiProject1.DilbertService.DilbertSoap.DailyDilbert(ApiProject1.DilbertService.DailyDilbertRequest request) {
            return base.Channel.DailyDilbert(request);
        }
        
        public string DailyDilbert(System.DateTime ADate) {
            ApiProject1.DilbertService.DailyDilbertRequest inValue = new ApiProject1.DilbertService.DailyDilbertRequest();
            inValue.Body = new ApiProject1.DilbertService.DailyDilbertRequestBody();
            inValue.Body.ADate = ADate;
            ApiProject1.DilbertService.DailyDilbertResponse retVal = ((ApiProject1.DilbertService.DilbertSoap)(this)).DailyDilbert(inValue);
            return retVal.Body.DailyDilbertResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApiProject1.DilbertService.DailyDilbertResponse> ApiProject1.DilbertService.DilbertSoap.DailyDilbertAsync(ApiProject1.DilbertService.DailyDilbertRequest request) {
            return base.Channel.DailyDilbertAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApiProject1.DilbertService.DailyDilbertResponse> DailyDilbertAsync(System.DateTime ADate) {
            ApiProject1.DilbertService.DailyDilbertRequest inValue = new ApiProject1.DilbertService.DailyDilbertRequest();
            inValue.Body = new ApiProject1.DilbertService.DailyDilbertRequestBody();
            inValue.Body.ADate = ADate;
            return ((ApiProject1.DilbertService.DilbertSoap)(this)).DailyDilbertAsync(inValue);
        }
    }
}
